ATACAR = "Atacar"
BLACK = (0, 0, 0)
BUTTON_SPACING = 20
BUTTON_WIDTH = 150
CONCENTRARSE = "Concentrarse"
DARK_GRAY = (105, 105, 105)
DEFENDER = "Defender"
DESCANSAR = "Descansar"
ENEMY = "Enemy"
GAME_NAME = "Combate Concurrente"
GRAY = (169, 169, 169)
INITIAL_HEIGHT = 768
INITIAL_WIDTH = 1024
NAME_FOLDER_CHARACTERS = "characters"
NAME_FOLDER_SPRITES = "sprites"
PLAYER = "Player"
TOTAL_BUTTONS = 4
URL_API = "https://pokeapi.co/api/v2/pokemon/"
WHITE = (255, 255, 255)
